### PR TITLE
Enhance to post action

### PR DESCRIPTION
**Pull request by spartan-ductduong**
# What
- Run git stash before locking to avoid failure if the working directory is not clean.
- Run git-crypt unlock on all keys.

# Why
- Ensure the post-action works without failure
- Lock all Git-Crypt keys in the existing project

### CODE REVIEW

**Comment by scheatkode** [comment]
Thanks !

I'm okay merging this as-is, but since this is a post-job, wouldn't something along these lines be more suitable ?

```diff
diff --git a/post.sh b/post.sh
index 693567389394..b543a42b174f 100755
--- a/post.sh
+++ b/post.sh
@@ -1,3 +1,3 @@
 #!/bin/sh
 
-git-crypt lock
+git-crypt lock -af
```

**Comment by spartan-ductduong** [comment]
> Thanks !
> 
> I'm okay merging this as-is, but since this is a post-job, wouldn't something along these lines be more suitable ?
> 
> ```diff
> diff --git a/post.sh b/post.sh
> index 693567389394..b543a42b174f 100755
> --- a/post.sh
> +++ b/post.sh
> @@ -1,3 +1,3 @@
>  #!/bin/sh
>  
> -git-crypt lock
> +git-crypt lock -af
> ```

Yes. That change is more suitable. I've updated my PR. Thanks!

**Comment by scheatkode** [comment]
Awesome, thank you !

**Comment by spartan-ductduong** [comment]
@scheatkode Could you please create a release for this change? Thanks!

**Comment by scheatkode** [comment]
@spartan-ductduong: I thought I included your changes in v0.1.3. :facepalm: It's available now as [v0.1.4](https://github.com/amplium/git-crypt-action/releases/tag/v0.1.4). Thank you for your patience.

**Comment by spartan-ductduong** [comment]
@scheatkode  Awesome. Thanks!

**Pull request merged**
