### PR TITLE
Use image version v0.1.4

### PR DESCRIPTION
**Pull request by spartan-ducduong**
Bump the image version in the `action.yaml` file to v0.1.4

### CODE REVIEW

**Comment by scheatkode** [comment]
Thanks !

**Comment by spartan-ductduong** [comment]
@scheatkode Thanks for merging my PR! Could you please also create a new release for this change?

**Comment by scheatkode** [comment]
@spartan-ductduong All good, release v0.1.5 has the necessary changes and it's reflected in the action.

**Comment by spartan-ducduong** [comment]
Awesome. Thanks for your support!

**Pull request merged**
